// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {rimage} from '../models';

export function CancelHandleFiles():Promise<void>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFilesDialog():Promise<void>;

export function StartHandleFiles(arg1:Array<string>,arg2:rimage.ImageOptions):Promise<void>;
