// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelHandleFiles() {
  return window['go']['rmanager']['FileManager']['CancelHandleFiles']();
}

export function OnStartup(arg1) {
  return window['go']['rmanager']['FileManager']['OnStartup'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['rmanager']['FileManager']['OpenDirectoryDialog']();
}

export function OpenFilesDialog() {
  return window['go']['rmanager']['FileManager']['OpenFilesDialog']();
}

export function StartHandleFiles(arg1, arg2) {
  return window['go']['rmanager']['FileManager']['StartHandleFiles'](arg1, arg2);
}
