// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnStartup(arg1) {
  return window['go']['rmanager']['TypeManager']['OnStartup'](arg1);
}

export function OutputImagesTypes() {
  return window['go']['rmanager']['TypeManager']['OutputImagesTypes']();
}

export function ResampleFilterTypes() {
  return window['go']['rmanager']['TypeManager']['ResampleFilterTypes']();
}
