// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {rimage} from '../models';

export function OnStartup(arg1:context.Context):Promise<void>;

export function OutputImagesTypes():Promise<Array<rimage.SupportedOutputImageType>>;

export function ResampleFilterTypes():Promise<Array<rimage.SupportedResampleFilterType>>;
